import { Inter } from "next/font/google";
import "@/common/styles/index.scss";
import "react-multi-carousel/lib/styles.css";
import Footer from "@/common/components/Footer";
import NYCNavbar from "@/common/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://kit.fontawesome.com/80b085e3c2.js"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={inter.className}>
        <NYCNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
